In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('online_retail_real_world.csv')
df

,OrderID,CustomerID,ProductName,Brand,Raw_Weight,Country,OrderDate,UnitPrice
0,REC-861088,6120,Perly,Perly,100 g,"Morocco,United States",2024-02-22,13.18
1,REC-900952,12550,Prince Goût Chocolat,LU,300 g,"Algeria,Belgium,France,French Polynesia,German...",2024-11-13,1.50
2,REC-595965,6705,Excellence Noir Prodigieux 90% Cacao,"Lindt EXCELLENCE,Lindt",100g,"Argelia,Austria,Bélgica,Bulgaria,Canadá,Repúbl...",2025-02-02,12.99
3,REC-942653,8645,Tonik,عربي,22 g,Maroc,2024-12-11,14.82
4,REC-885998,14430,Sésame,Gerblé,230g,"Belgium, Bulgaria, France, en:switzerland",2025-08-21,18.40
...,...,...,...,...,...,...,...,...
2995,REC-867989,13739,Cocoa Orange,Nakd,NaN,en:GB,2025-03-30,3.78
2996,REC-774268,8212,Chocolate For Change Dark Chocolate With Orange,Coop,100 g,"Germany,en:united-kingdom",2025-03-23,14.41
2997,REC-432494,13398,Lait dessert,Fin Carré,200 g,"France, en:united-kingdom",2025-01-03,17.58
2998,REC-117507,8050,Rusticotti,Balocco,700,"Francia,Italia",2025-09-02,21.35
2999,REC-692469,11809,Cheddar & Onion Chutney Rolls,Higgidy,160g,en:gb,2024-12-07,7.47

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      3000 non-null   object
 1   CustomerID   3000 non-null   int64
 2   ProductName  2904 non-null   object
 3   Brand        2665 non-null   object
 4   Raw_Weight   2488 non-null   object
 5   Country      3000 non-null   object
 6   OrderDate    3000 non-null   object
 7   UnitPrice    2615 non-null   float64
dtypes: float64(1), int64(1), object(6)
memory usage: 187.6+ KB

In [4]:
df.describe()

         CustomerID    UnitPrice
count   3000.000000  2615.000000
mean    9989.842333    12.992417
std     2871.959873     6.963856
min     5011.000000     1.000000
25%     7454.750000     6.985000
50%    10066.000000    13.160000
75%    12527.250000    18.960000
max    14998.000000    24.990000

In [5]:
df.isna().sum()

OrderID          0
CustomerID       0
ProductName     96
Brand          335
Raw_Weight     512
Country          0
OrderDate        0
UnitPrice      385
dtype: int64

In [6]:
df['ProductName'].value_counts()

ProductName
Petit beurre                          5
Cream Crackers                        5
Dark Chocolate                        5
Lentil Chips                          4
Pringles Original                     4
                                     ..
Excellence Noir Puissant 85% Cacao    1
Fourrés Chocolat Noir                 1
Extra dark 74% Cocoa                  1
FIBRES                                1
Prince Goût Chocolat                  1
Name: count, Length: 2726, dtype: int64

In [7]:
df['Brand'].value_counts()

Brand
Gerblé                  55
Hacendado               50
Carrefour               41
Gullón                  40
Lindt                   40
                        ..
Benenuts                 1
Duc de Coeur, Sondey     1
Bellarom                 1
Nomo                     1
Perly                    1
Name: count, Length: 1110, dtype: int64

In [11]:
df['Brand'] = df['Brand'].fillna('missing')

In [12]:
df['Brand'].value_counts()

Brand
missing                 335
Gerblé                   55
Hacendado                50
Carrefour                41
Lindt                    40
                       ...
Feastables, MrBeast       1
Wrigley‘s,extraFresh      1
Dolciando, Eurospin       1
Kinder, คินเดอร์          1
Rio                       1
Name: count, Length: 1111, dtype: int64

In [18]:
product_name_mode = df['ProductName'].mode()[0]
product_name_mode

'Cream Crackers'

In [19]:
df['ProductName'] = df['ProductName'].fillna(product_name_mode)

In [20]:
df['ProductName'].value_counts()

ProductName
Cream Crackers                        101
Dark Chocolate                          5
Petit beurre                            5
Lentil Chips                            4
Pringles Original                       4
                                     ...
Excellence Noir Puissant 85% Cacao      1
Fourrés Chocolat Noir                   1
Extra dark 74% Cocoa                    1
FIBRES                                  1
Prince Goût Chocolat                    1
Name: count, Length: 2726, dtype: int64

In [21]:
df.isna().sum()

OrderID          0
CustomerID       0
ProductName      0
Brand            0
Raw_Weight     512
Country          0
OrderDate        0
UnitPrice      385
dtype: int64

In [ ]:
df['Raw_Weight'] = df['Raw_Weight'].astype(str).str.replace('g', '' ,case=False).str.strip()

In [23]:
df

,OrderID,CustomerID,ProductName,Brand,Raw_Weight,Country,OrderDate,UnitPrice
0,REC-861088,6120,Perly,Perly,100,"Morocco,United States",2024-02-22,13.18
1,REC-900952,12550,Prince Goût Chocolat,LU,300,"Algeria,Belgium,France,French Polynesia,German...",2024-11-13,1.50
2,REC-595965,6705,Excellence Noir Prodigieux 90% Cacao,"Lindt EXCELLENCE,Lindt",100,"Argelia,Austria,Bélgica,Bulgaria,Canadá,Repúbl...",2025-02-02,12.99
3,REC-942653,8645,Tonik,عربي,22,Maroc,2024-12-11,14.82
4,REC-885998,14430,Sésame,Gerblé,230,"Belgium, Bulgaria, France, en:switzerland",2025-08-21,18.40
...,...,...,...,...,...,...,...,...
2995,REC-867989,13739,Cocoa Orange,Nakd,nan,en:GB,2025-03-30,3.78
2996,REC-774268,8212,Chocolate For Change Dark Chocolate With Orange,Coop,100,"Germany,en:united-kingdom",2025-03-23,14.41
2997,REC-432494,13398,Lait dessert,Fin Carré,200,"France, en:united-kingdom",2025-01-03,17.58
2998,REC-117507,8050,Rusticotti,Balocco,700,"Francia,Italia",2025-09-02,21.35
2999,REC-692469,11809,Cheddar & Onion Chutney Rolls,Higgidy,160,en:gb,2024-12-07,7.47

In [26]:
df['Raw_Weight'] = pd.to_numeric(df['Raw_Weight'], errors='coerce')
raw_weight_mean = df['Raw_Weight'].mean()
raw_weight_mean

np.float64(190.95944280078896)

In [27]:
df['Raw_Weight'] = df['Raw_Weight'].fillna(raw_weight_mean)

In [28]:
df.isna().sum()

OrderID          0
CustomerID       0
ProductName      0
Brand            0
Raw_Weight       0
Country          0
OrderDate        0
UnitPrice      385
dtype: int64

In [29]:
UnitPrice_mean = df['UnitPrice'].mean()
UnitPrice_mean

np.float64(12.992416826003824)

In [30]:
df['UnitPrice'] = df['UnitPrice'].fillna(UnitPrice_mean)

In [31]:
df.isna().sum()

OrderID        0
CustomerID     0
ProductName    0
Brand          0
Raw_Weight     0
Country        0
OrderDate      0
UnitPrice      0
dtype: int64